# Generated by Django 5.1.2 on 2024-10-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_pen_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="pen",
            name="title",
            field=models.CharField(default="test", max_length=30),
            preserve_default=False,
        ),
    ]
