# Generated by Django 5.1.2 on 2025-01-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_conversation_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="last_message",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
