# Generated by Django 5.1.2 on 2025-01-20 00:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_message_is_read"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="created_at",
            new_name="created",
        ),
    ]
