# Generated by Django 5.1.2 on 2025-01-21 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_rename_created_at_message_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
