# Generated by Django 5.1.2 on 2025-01-21 08:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_conversation_is_read"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="is_read",
        ),
    ]
