# Generated by Django 5.1.2 on 2025-01-22 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_remove_conversation_is_read"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="last_conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.conversation",
            ),
        ),
    ]
