# Generated by Django 5.1.2 on 2025-01-28 04:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_alter_profile_last_conversation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="following",
        ),
    ]
