# Generated by Django 5.1.2 on 2025-02-16 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_profile_following"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conversation",
            old_name="updated",
            new_name="modified",
        ),
        migrations.AlterField(
            model_name="pen",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
