# Generated by Django 5.1.2 on 2025-02-18 00:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_rename_updated_conversation_modified_alter_pen_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="demo",
            new_name="is_demo",
        ),
    ]
