# Generated by Django 5.1.2 on 2025-02-18 00:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_rename_demo_profile_is_demo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pen",
            old_name="public",
            new_name="is_public",
        ),
    ]
