# Generated by Django 5.1.2 on 2024-12-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_profile_user"),
        ("core", "0002_alter_pen_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="pinned_items",
            field=models.ManyToManyField(related_name="pinned_profiles", to="core.pen"),
        ),
    ]
